// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoKHfVQAphUpDUMnCzfCTszgNoMa6Ui8',
    appId: '1:713070198848:web:ba12391cb258e36f0a5fa5',
    messagingSenderId: '713070198848',
    projectId: 'mitramanas-ba305',
    authDomain: 'mitramanas-ba305.firebaseapp.com',
    storageBucket: 'mitramanas-ba305.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGofeWqLeshmb69XiqaCDLonYhBXjqW4',
    appId: '1:713070198848:android:83f6074a55e081af0a5fa5',
    messagingSenderId: '713070198848',
    projectId: 'mitramanas-ba305',
    storageBucket: 'mitramanas-ba305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJa33jhR3YgcR_cdRLQGL3bDqM_jybUSQ',
    appId: '1:713070198848:ios:a7342d4a9f0dd51e0a5fa5',
    messagingSenderId: '713070198848',
    projectId: 'mitramanas-ba305',
    storageBucket: 'mitramanas-ba305.firebasestorage.app',
    iosBundleId: 'com.example.mitramanas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJa33jhR3YgcR_cdRLQGL3bDqM_jybUSQ',
    appId: '1:713070198848:ios:a7342d4a9f0dd51e0a5fa5',
    messagingSenderId: '713070198848',
    projectId: 'mitramanas-ba305',
    storageBucket: 'mitramanas-ba305.firebasestorage.app',
    iosBundleId: 'com.example.mitramanas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnoKHfVQAphUpDUMnCzfCTszgNoMa6Ui8',
    appId: '1:713070198848:web:0eef8f1c394a9f400a5fa5',
    messagingSenderId: '713070198848',
    projectId: 'mitramanas-ba305',
    authDomain: 'mitramanas-ba305.firebaseapp.com',
    storageBucket: 'mitramanas-ba305.firebasestorage.app',
  );
}
